/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedMarketAnalysisRouteImport } from './routes/_authenticated/market-analysis'
import { Route as AuthenticatedMarketingIdeasRouteImport } from './routes/_authenticated/marketing-ideas'
import { Route as AuthenticatedOpportunitiesRouteImport } from './routes/_authenticated/opportunities'

const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/_authenticated/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedMarketAnalysisRoute =
  AuthenticatedMarketAnalysisRouteImport.update({
    id: '/_authenticated/market-analysis',
    path: '/market-analysis',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedMarketingIdeasRoute =
  AuthenticatedMarketingIdeasRouteImport.update({
    id: '/_authenticated/marketing-ideas',
    path: '/marketing-ideas',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedOpportunitiesRoute =
  AuthenticatedOpportunitiesRouteImport.update({
    id: '/_authenticated/opportunities',
    path: '/opportunities',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/market-analysis': typeof AuthenticatedMarketAnalysisRoute
  '/marketing-ideas': typeof AuthenticatedMarketingIdeasRoute
  '/opportunities': typeof AuthenticatedOpportunitiesRoute
  '/': typeof AuthenticatedIndexRoute
}
export interface FileRoutesByTo {
  '/market-analysis': typeof AuthenticatedMarketAnalysisRoute
  '/marketing-ideas': typeof AuthenticatedMarketingIdeasRoute
  '/opportunities': typeof AuthenticatedOpportunitiesRoute
  '/': typeof AuthenticatedIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated/market-analysis': typeof AuthenticatedMarketAnalysisRoute
  '/_authenticated/marketing-ideas': typeof AuthenticatedMarketingIdeasRoute
  '/_authenticated/opportunities': typeof AuthenticatedOpportunitiesRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/market-analysis' | '/marketing-ideas' | '/opportunities' | '/'
  fileRoutesByTo: FileRoutesByTo
  to: '/market-analysis' | '/marketing-ideas' | '/opportunities' | '/'
  id:
    | '__root__'
    | '/_authenticated/market-analysis'
    | '/_authenticated/marketing-ideas'
    | '/_authenticated/opportunities'
    | '/_authenticated/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedMarketAnalysisRoute: typeof AuthenticatedMarketAnalysisRoute
  AuthenticatedMarketingIdeasRoute: typeof AuthenticatedMarketingIdeasRoute
  AuthenticatedOpportunitiesRoute: typeof AuthenticatedOpportunitiesRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/market-analysis': {
      id: '/_authenticated/market-analysis'
      path: '/market-analysis'
      fullPath: '/market-analysis'
      preLoaderRoute: typeof AuthenticatedMarketAnalysisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/marketing-ideas': {
      id: '/_authenticated/marketing-ideas'
      path: '/marketing-ideas'
      fullPath: '/marketing-ideas'
      preLoaderRoute: typeof AuthenticatedMarketingIdeasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/opportunities': {
      id: '/_authenticated/opportunities'
      path: '/opportunities'
      fullPath: '/opportunities'
      preLoaderRoute: typeof AuthenticatedOpportunitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedMarketAnalysisRoute: AuthenticatedMarketAnalysisRoute,
  AuthenticatedMarketingIdeasRoute: AuthenticatedMarketingIdeasRoute,
  AuthenticatedOpportunitiesRoute: AuthenticatedOpportunitiesRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
